version: "3.8"
services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        #environment:
            #- MONGO_INITDB_ROOT_USERNAME: root
            #- MONGO_INITDB_ROOT_PASSWORD: 123
        ports:
          - 27017:27017
        volumes:
          - mongo_data:/data/db
        restart: always
    postgres:
        container_name: postgresql
        image: postgres:16.2
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=MottuDB
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            # data persistence
            - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
            # data mapping -> host: container
            # queues and messages data of the container will be stored on the host
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        restart: always
    redis:
        container_name: redis
        image: redis
        ports:
          - 6379:6379
        volumes:
          - /myredis/conf:/usr/local/etc/redis
        restart: always        
volumes:
    postgres_data:
    mongo_data:
