// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mottu.Infrastructure.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mottu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mottu.Domain.Entities.AcceptedOrder", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AcceptedDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("Accepted_Date");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Accepted_Orders", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BirthDate");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Cnh")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CNH");

                    b.Property<Guid?>("CnhTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CNPJ");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_Active");

                    b.Property<bool>("IsDelivering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Is_Delivering");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("PathCnhImage")
                        .HasColumnType("text")
                        .HasColumnName("Path_CNH_Image");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CnhTypeId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d277ec2-3b50-4920-9bab-422693f6017b"),
                            Cnh = "***",
                            Cnpj = "***",
                            IsActive = true,
                            IsDelivering = false,
                            Login = "admin",
                            Name = "administrator",
                            Password = "123",
                            UserTypeId = new Guid("f6a2372a-b146-45f9-be70-a0be13736dd8")
                        });
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Bike", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLeased")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Year");

                    b.Property<string>("_model")
                        .HasColumnType("text");

                    b.Property<string>("_plate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("Plate");

                    b.ToTable("Bike", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.CnhType", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Cnh_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11dcfe4c-c66a-47de-8b88-81f830919085"),
                            Name = "A"
                        },
                        new
                        {
                            Id = new Guid("9b39cb59-7300-4634-a23b-5cac5017dbb6"),
                            Name = "B"
                        },
                        new
                        {
                            Id = new Guid("63ad311d-c292-4374-8916-eb083be610b8"),
                            Name = "AB"
                        },
                        new
                        {
                            Id = new Guid("f4958544-c796-43f4-a3cb-568ef6272a8d"),
                            Name = "NA"
                        });
                });

            modelBuilder.Entity("Mottu.Domain.Entities.DeliveredOrder", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DeliveredDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("Delivered_Date");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Delivered_Orders", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.NotificatedUser", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NotificationDate")
                        .HasColumnType("date")
                        .HasColumnName("Notification_Date");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("Notificated_User", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NotificationDate")
                        .HasColumnType("date")
                        .HasColumnName("Notification_Date");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Order", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOrder")
                        .HasColumnType("date")
                        .HasColumnName("Date_Order");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<Guid?>("StatusOrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("ValueOrder")
                        .HasColumnType("double precision")
                        .HasColumnName("Value_Order");

                    b.HasKey("Id");

                    b.HasIndex("StatusOrderId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DailyValue")
                        .HasColumnType("double precision")
                        .HasColumnName("Daily_Value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<int>("FinePercentage")
                        .HasColumnType("integer")
                        .HasColumnName("Fine_Percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<int>("NumDays")
                        .HasColumnType("integer")
                        .HasColumnName("Num_Days");

                    b.HasKey("Id");

                    b.ToTable("Plan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71cada4b-0fb0-40be-92f0-fe9b1534816c"),
                            DailyValue = 30.0,
                            Description = "Plano de locação de 7 dias",
                            FinePercentage = 20,
                            Name = "Plano 7 dias",
                            NumDays = 7
                        },
                        new
                        {
                            Id = new Guid("f492d76b-e54b-4d86-8772-bcc095cc8167"),
                            DailyValue = 28.0,
                            Description = "Plano de locação de 15 dias",
                            FinePercentage = 40,
                            Name = "Plano 15 dias",
                            NumDays = 15
                        },
                        new
                        {
                            Id = new Guid("4183ed75-08df-4272-8c91-44fd63c43dae"),
                            DailyValue = 22.0,
                            Description = "Plano de locação de 30 dias",
                            FinePercentage = 60,
                            Name = "Plano 30 dias",
                            NumDays = 30
                        });
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("Creation_Date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("End_Date");

                    b.Property<DateOnly>("InitialDate")
                        .HasColumnType("date")
                        .HasColumnName("Initial_Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Active");

                    b.Property<int>("NumMoreDailys")
                        .HasColumnType("integer")
                        .HasColumnName("Num_More_Dailys");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PredictionDate")
                        .HasColumnType("date")
                        .HasColumnName("Predition_Date");

                    b.Property<double>("TotalValue")
                        .HasColumnType("double precision")
                        .HasColumnName("Total_Value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Rental", (string)null);
                });

            modelBuilder.Entity("Mottu.Domain.Entities.StatusOrder", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status_Order", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cb64fd3-7080-41ea-9574-af6b2a16f8e9"),
                            Name = "DISPONÍVEL",
                            _name = "DISPONÍVEL"
                        },
                        new
                        {
                            Id = new Guid("a0996df0-919c-4873-8f22-20cf5d680da0"),
                            Name = "ACEITO",
                            _name = "ACEITO"
                        },
                        new
                        {
                            Id = new Guid("d1979c80-6c15-4268-9e68-010f53570498"),
                            Name = "ENTREGUE",
                            _name = "ENTREGUE"
                        });
                });

            modelBuilder.Entity("Mottu.Domain.Entities.UserType", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a2372a-b146-45f9-be70-a0be13736dd8"),
                            Name = "ADMINISTRADOR",
                            _name = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("bbd4ed2e-5f92-414c-9f7b-e7395c464898"),
                            Name = "ENTREGADOR",
                            _name = "ENTREGADOR"
                        },
                        new
                        {
                            Id = new Guid("79fd21e3-3127-4dda-ba1b-17d20a9d1d3e"),
                            Name = "CONSUMIDOR",
                            _name = "CONSUMIDOR"
                        });
                });

            modelBuilder.Entity("Mottu.Domain.Entities.AcceptedOrder", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Order", "Order")
                        .WithMany("AcceptedOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Domain.Entities.AppUser", "User")
                        .WithMany("AcceptedOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.CnhType", "CnhType")
                        .WithMany()
                        .HasForeignKey("CnhTypeId");

                    b.HasOne("Mottu.Domain.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CnhType");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.DeliveredOrder", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Order", "Order")
                        .WithMany("DeliveredOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Domain.Entities.AppUser", "User")
                        .WithMany("DeliveredOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.NotificatedUser", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Notification", "Notification")
                        .WithMany("NotificatedUsers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Domain.Entities.AppUser", "User")
                        .WithMany("NotificatedUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Order", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.StatusOrder", "StatusOrder")
                        .WithMany()
                        .HasForeignKey("StatusOrderId");

                    b.Navigation("StatusOrder");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Rental", b =>
                {
                    b.HasOne("Mottu.Domain.Entities.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AcceptedOrders");

                    b.Navigation("DeliveredOrders");

                    b.Navigation("NotificatedUsers");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Notification", b =>
                {
                    b.Navigation("NotificatedUsers");
                });

            modelBuilder.Entity("Mottu.Domain.Entities.Order", b =>
                {
                    b.Navigation("AcceptedOrders");

                    b.Navigation("DeliveredOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
